In [110]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
import numpy as np
import csv
import os

# training
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard


In [111]:

DATA_PATH = os.path.join('MP_Data')  # Path for exported data, numpy arrays


#getting dataset values from csv
with open('newlabelstrain.csv', newline='') as f:
    reader = csv.reader(f)
    data = [row[0] for row in reader]


actions = np.array(data)
no_sequences = 30  # thirty videos worth of data
sequence_length = 30  # each video is 30 frame in length

label_map = {label:num for num, label in enumerate(actions)}
print(label_map)


{'niceto': 0, 'yo': 1, 'meetyou': 2, 'thumbsup': 3, 'hi': 4}


In [112]:

sequences, labels = [], []  # x data, y data
for action in actions:
    for sequence in range(no_sequences):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

x = np.array(sequences)
print(x.shape)
y = to_categorical(labels).astype(int)
print(y)


(150, 30, 1662)
[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0

In [113]:

# creating training partitions
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.05)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(142, 30, 1662) (8, 30, 1662) (142, 5) (8, 5)


In [114]:

# training

log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

model = Sequential() # instantiating the model
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(30, 1662)))
model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(LSTM(64, return_sequences=False, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [115]:
model.fit(x_train, y_train, epochs=2000, callbacks=[tb_callback])
print(model.summary())

Epoch 1/2000
5/5 [==============================] - 3s 167ms/step - loss: 1.6931 - categorical_accuracy: 0.2254
Epoch 2/2000
5/5 [==============================] - 0s 60ms/step - loss: 1.6363 - categorical_accuracy: 0.2042
Epoch 3/2000
5/5 [==============================] - 0s 61ms/step - loss: 1.5970 - categorical_accuracy: 0.2042
Epoch 4/2000
5/5 [==============================] - 0s 73ms/step - loss: 1.5732 - categorical_accuracy: 0.2042
Epoch 5/2000
5/5 [==============================] - 0s 71ms/step - loss: 1.5605 - categorical_accuracy: 0.1268
Epoch 6/2000
5/5 [==============================] - 0s 71ms/step - loss: 1.8119 - categorical_accuracy: 0.2113
Epoch 7/2000
5/5 [==============================] - 0s 60ms/step - loss: 1.5356 - categorical_accuracy: 0.2887
Epoch 8/2000
5/5 [==============================] - 0s 61ms/step - loss: 1.5093 - categorical_accuracy: 0.2254
Epoch 9/2000
5/5 [==============================] - 0s 60ms/step - loss: 1.5580 - categorical_accuracy: 0.3732


5/5 [==============================] - 0s 59ms/step - loss: 0.6102 - categorical_accuracy: 0.6549
Epoch 75/2000
5/5 [==============================] - 0s 57ms/step - loss: 0.5900 - categorical_accuracy: 0.7183
Epoch 76/2000
5/5 [==============================] - 0s 66ms/step - loss: 0.6200 - categorical_accuracy: 0.7183
Epoch 77/2000
5/5 [==============================] - 0s 62ms/step - loss: 0.5913 - categorical_accuracy: 0.6761
Epoch 78/2000
5/5 [==============================] - 0s 68ms/step - loss: 0.5559 - categorical_accuracy: 0.7183
Epoch 79/2000
5/5 [==============================] - 0s 60ms/step - loss: 0.5725 - categorical_accuracy: 0.7183
Epoch 80/2000
5/5 [==============================] - 0s 61ms/step - loss: 0.5355 - categorical_accuracy: 0.6972
Epoch 81/2000
5/5 [==============================] - 0s 61ms/step - loss: 0.5415 - categorical_accuracy: 0.7394
Epoch 82/2000
5/5 [==============================] - 0s 63ms/step - loss: 0.5490 - categorical_accuracy: 0.7535
Epoch 

5/5 [==============================] - 0s 58ms/step - loss: 0.3950 - categorical_accuracy: 0.8099
Epoch 147/2000
5/5 [==============================] - 0s 57ms/step - loss: 0.4593 - categorical_accuracy: 0.7746
Epoch 148/2000
5/5 [==============================] - 0s 57ms/step - loss: 0.3398 - categorical_accuracy: 0.8521
Epoch 149/2000
5/5 [==============================] - 0s 58ms/step - loss: 6.3583 - categorical_accuracy: 0.8451
Epoch 150/2000
5/5 [==============================] - 0s 57ms/step - loss: 0.3535 - categorical_accuracy: 0.8380
Epoch 151/2000
5/5 [==============================] - 0s 58ms/step - loss: 0.4785 - categorical_accuracy: 0.7746
Epoch 152/2000
5/5 [==============================] - 0s 59ms/step - loss: 0.4171 - categorical_accuracy: 0.8099
Epoch 153/2000
5/5 [==============================] - 0s 57ms/step - loss: 0.3740 - categorical_accuracy: 0.8521
Epoch 154/2000
5/5 [==============================] - 0s 57ms/step - loss: 0.3656 - categorical_accuracy: 0.859

5/5 [==============================] - 0s 57ms/step - loss: 0.5085 - categorical_accuracy: 0.7535
Epoch 219/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.4052 - categorical_accuracy: 0.8099
Epoch 220/2000
5/5 [==============================] - 0s 54ms/step - loss: 0.3478 - categorical_accuracy: 0.8732
Epoch 221/2000
5/5 [==============================] - 0s 54ms/step - loss: 0.3109 - categorical_accuracy: 0.8944
Epoch 222/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.7172 - categorical_accuracy: 0.7958
Epoch 223/2000
5/5 [==============================] - 0s 55ms/step - loss: 1.6246 - categorical_accuracy: 0.4437
Epoch 224/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.9780 - categorical_accuracy: 0.5704
Epoch 225/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.9878 - categorical_accuracy: 0.4930
Epoch 226/2000
5/5 [==============================] - 0s 54ms/step - loss: 0.8468 - categorical_accuracy: 0.570

5/5 [==============================] - 0s 56ms/step - loss: 0.2398 - categorical_accuracy: 0.8803
Epoch 291/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.3371 - categorical_accuracy: 0.8451
Epoch 292/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.3993 - categorical_accuracy: 0.8380
Epoch 293/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.3987 - categorical_accuracy: 0.8099
Epoch 294/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.3799 - categorical_accuracy: 0.8169
Epoch 295/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.3725 - categorical_accuracy: 0.8239
Epoch 296/2000
5/5 [==============================] - 0s 54ms/step - loss: 0.4720 - categorical_accuracy: 0.7606
Epoch 297/2000
5/5 [==============================] - 0s 54ms/step - loss: 0.3480 - categorical_accuracy: 0.8451
Epoch 298/2000
5/5 [==============================] - 0s 57ms/step - loss: 0.4357 - categorical_accuracy: 0.795

5/5 [==============================] - 0s 56ms/step - loss: 0.2397 - categorical_accuracy: 0.9014
Epoch 363/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.2280 - categorical_accuracy: 0.8873
Epoch 364/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.2418 - categorical_accuracy: 0.8803
Epoch 365/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.2091 - categorical_accuracy: 0.8944
Epoch 366/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.1924 - categorical_accuracy: 0.9155
Epoch 367/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.1770 - categorical_accuracy: 0.9366
Epoch 368/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.1820 - categorical_accuracy: 0.9014
Epoch 369/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.1641 - categorical_accuracy: 0.9296
Epoch 370/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.2218 - categorical_accuracy: 0.894

5/5 [==============================] - 0s 55ms/step - loss: 1.6087 - categorical_accuracy: 0.1972
Epoch 435/2000
5/5 [==============================] - 0s 56ms/step - loss: 1.6087 - categorical_accuracy: 0.1972
Epoch 436/2000
5/5 [==============================] - 0s 56ms/step - loss: 1.6087 - categorical_accuracy: 0.1972
Epoch 437/2000
5/5 [==============================] - 0s 54ms/step - loss: 1.6084 - categorical_accuracy: 0.2042
Epoch 438/2000
5/5 [==============================] - 0s 55ms/step - loss: 1.6080 - categorical_accuracy: 0.1972
Epoch 439/2000
5/5 [==============================] - 0s 55ms/step - loss: 1.6076 - categorical_accuracy: 0.1972
Epoch 440/2000
5/5 [==============================] - 0s 54ms/step - loss: 1.6075 - categorical_accuracy: 0.1972
Epoch 441/2000
5/5 [==============================] - 0s 55ms/step - loss: 1.6080 - categorical_accuracy: 0.1831
Epoch 442/2000
5/5 [==============================] - 0s 56ms/step - loss: 1.6077 - categorical_accuracy: 0.197

5/5 [==============================] - 0s 57ms/step - loss: 0.5349 - categorical_accuracy: 0.8521
Epoch 507/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.5108 - categorical_accuracy: 0.8662
Epoch 508/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.4836 - categorical_accuracy: 0.8732
Epoch 509/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.4528 - categorical_accuracy: 0.8521
Epoch 510/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.4217 - categorical_accuracy: 0.8732
Epoch 511/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.4013 - categorical_accuracy: 0.8592
Epoch 512/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.3912 - categorical_accuracy: 0.8662
Epoch 513/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.7872 - categorical_accuracy: 0.8662
Epoch 514/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.4086 - categorical_accuracy: 0.873

5/5 [==============================] - 0s 56ms/step - loss: 0.2632 - categorical_accuracy: 0.8732
Epoch 579/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.3314 - categorical_accuracy: 0.8380
Epoch 580/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.5129 - categorical_accuracy: 0.7746
Epoch 581/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.3778 - categorical_accuracy: 0.8239
Epoch 582/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.4081 - categorical_accuracy: 0.8169
Epoch 583/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.4868 - categorical_accuracy: 0.8169
Epoch 584/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.3245 - categorical_accuracy: 0.8662
Epoch 585/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.3010 - categorical_accuracy: 0.8310
Epoch 586/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.3417 - categorical_accuracy: 0.859

5/5 [==============================] - 0s 56ms/step - loss: 0.1700 - categorical_accuracy: 0.9225
Epoch 651/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.1380 - categorical_accuracy: 0.9296
Epoch 652/2000
5/5 [==============================] - 0s 61ms/step - loss: 0.1277 - categorical_accuracy: 0.9577
Epoch 653/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.2021 - categorical_accuracy: 0.9014
Epoch 654/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.1448 - categorical_accuracy: 0.9296
Epoch 655/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.1200 - categorical_accuracy: 0.9577
Epoch 656/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.1198 - categorical_accuracy: 0.9437
Epoch 657/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.1214 - categorical_accuracy: 0.9507
Epoch 658/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.1350 - categorical_accuracy: 0.943

5/5 [==============================] - 0s 50ms/step - loss: 0.0967 - categorical_accuracy: 0.9507
Epoch 723/2000
5/5 [==============================] - 0s 52ms/step - loss: 0.1191 - categorical_accuracy: 0.9648
Epoch 724/2000
5/5 [==============================] - 0s 52ms/step - loss: 0.1233 - categorical_accuracy: 0.9507
Epoch 725/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.1131 - categorical_accuracy: 0.9577
Epoch 726/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.1132 - categorical_accuracy: 0.9437
Epoch 727/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.1425 - categorical_accuracy: 0.9437
Epoch 728/2000
5/5 [==============================] - 0s 52ms/step - loss: 0.3662 - categorical_accuracy: 0.8310
Epoch 729/2000
5/5 [==============================] - 0s 52ms/step - loss: 0.9964 - categorical_accuracy: 0.7606
Epoch 730/2000
5/5 [==============================] - 0s 52ms/step - loss: 0.3771 - categorical_accuracy: 0.845

5/5 [==============================] - 0s 52ms/step - loss: 0.0994 - categorical_accuracy: 0.9577
Epoch 795/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.0843 - categorical_accuracy: 0.9577
Epoch 796/2000
5/5 [==============================] - 0s 52ms/step - loss: 0.0796 - categorical_accuracy: 0.9718
Epoch 797/2000
5/5 [==============================] - 0s 52ms/step - loss: 0.0849 - categorical_accuracy: 0.9789
Epoch 798/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.0730 - categorical_accuracy: 0.9718
Epoch 799/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.0787 - categorical_accuracy: 0.9648
Epoch 800/2000
5/5 [==============================] - 0s 52ms/step - loss: 0.0988 - categorical_accuracy: 0.9507
Epoch 801/2000
5/5 [==============================] - 0s 52ms/step - loss: 0.0772 - categorical_accuracy: 0.9577
Epoch 802/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.0734 - categorical_accuracy: 0.971

5/5 [==============================] - 0s 51ms/step - loss: 0.2728 - categorical_accuracy: 0.8944
Epoch 867/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.1611 - categorical_accuracy: 0.9437
Epoch 868/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.1146 - categorical_accuracy: 0.9577
Epoch 869/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.0977 - categorical_accuracy: 0.9648
Epoch 870/2000
5/5 [==============================] - 0s 49ms/step - loss: 0.1179 - categorical_accuracy: 0.9437
Epoch 871/2000
5/5 [==============================] - 0s 59ms/step - loss: 0.1162 - categorical_accuracy: 0.9507
Epoch 872/2000
5/5 [==============================] - 0s 50ms/step - loss: 0.1766 - categorical_accuracy: 0.9296
Epoch 873/2000
5/5 [==============================] - 0s 49ms/step - loss: 0.0991 - categorical_accuracy: 0.9577
Epoch 874/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.0883 - categorical_accuracy: 0.971

5/5 [==============================] - 0s 51ms/step - loss: 0.0633 - categorical_accuracy: 0.9859
Epoch 939/2000
5/5 [==============================] - 0s 53ms/step - loss: 0.0731 - categorical_accuracy: 0.9648
Epoch 940/2000
5/5 [==============================] - 0s 50ms/step - loss: 0.0748 - categorical_accuracy: 0.9648
Epoch 941/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.0887 - categorical_accuracy: 0.9577
Epoch 942/2000
5/5 [==============================] - 0s 50ms/step - loss: 0.0847 - categorical_accuracy: 0.9718
Epoch 943/2000
5/5 [==============================] - 0s 52ms/step - loss: 0.1208 - categorical_accuracy: 0.9366
Epoch 944/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.1508 - categorical_accuracy: 0.9296
Epoch 945/2000
5/5 [==============================] - 0s 50ms/step - loss: 0.3961 - categorical_accuracy: 0.8380
Epoch 946/2000
5/5 [==============================] - 0s 51ms/step - loss: 0.1816 - categorical_accuracy: 0.894

5/5 [==============================] - 0s 61ms/step - loss: 0.0620 - categorical_accuracy: 0.9789
Epoch 1011/2000
5/5 [==============================] - 0s 70ms/step - loss: 0.0501 - categorical_accuracy: 0.9859
Epoch 1012/2000
5/5 [==============================] - 0s 57ms/step - loss: 0.0492 - categorical_accuracy: 0.9859
Epoch 1013/2000
5/5 [==============================] - 0s 85ms/step - loss: 0.0633 - categorical_accuracy: 0.9718
Epoch 1014/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.0669 - categorical_accuracy: 0.9718
Epoch 1015/2000
5/5 [==============================] - 0s 60ms/step - loss: 0.1148 - categorical_accuracy: 0.9507
Epoch 1016/2000
5/5 [==============================] - 0s 69ms/step - loss: 0.0613 - categorical_accuracy: 0.9718
Epoch 1017/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.0778 - categorical_accuracy: 0.9718
Epoch 1018/2000
5/5 [==============================] - 0s 85ms/step - loss: 0.0634 - categorical_accurac

Epoch 1082/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.0507 - categorical_accuracy: 0.9859
Epoch 1083/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.0454 - categorical_accuracy: 0.9859
Epoch 1084/2000
5/5 [==============================] - 0s 54ms/step - loss: 0.0453 - categorical_accuracy: 0.9930
Epoch 1085/2000
5/5 [==============================] - 0s 61ms/step - loss: 0.0449 - categorical_accuracy: 0.9859
Epoch 1086/2000
5/5 [==============================] - 0s 78ms/step - loss: 0.0420 - categorical_accuracy: 0.9930
Epoch 1087/2000
5/5 [==============================] - 0s 70ms/step - loss: 0.0473 - categorical_accuracy: 0.9789
Epoch 1088/2000
5/5 [==============================] - 0s 90ms/step - loss: 0.0422 - categorical_accuracy: 0.9930
Epoch 1089/2000
5/5 [==============================] - 0s 92ms/step - loss: 0.0382 - categorical_accuracy: 0.9859
Epoch 1090/2000
5/5 [==============================] - 1s 99ms/step - loss: 0.0416 - cat

5/5 [==============================] - 0s 80ms/step - loss: 0.1062 - categorical_accuracy: 0.9789
Epoch 1154/2000
5/5 [==============================] - 1s 92ms/step - loss: 0.0876 - categorical_accuracy: 0.9789
Epoch 1155/2000
5/5 [==============================] - 0s 90ms/step - loss: 0.0706 - categorical_accuracy: 0.9789
Epoch 1156/2000
5/5 [==============================] - 0s 95ms/step - loss: 0.0684 - categorical_accuracy: 0.9859
Epoch 1157/2000
5/5 [==============================] - 1s 103ms/step - loss: 0.0588 - categorical_accuracy: 0.9859
Epoch 1158/2000
5/5 [==============================] - 0s 86ms/step - loss: 0.0605 - categorical_accuracy: 0.9859
Epoch 1159/2000
5/5 [==============================] - 0s 96ms/step - loss: 0.0525 - categorical_accuracy: 0.9930
Epoch 1160/2000
5/5 [==============================] - 0s 100ms/step - loss: 0.0519 - categorical_accuracy: 0.9930
Epoch 1161/2000
5/5 [==============================] - 1s 104ms/step - loss: 0.0562 - categorical_accu

Epoch 1225/2000
5/5 [==============================] - 0s 71ms/step - loss: 0.0419 - categorical_accuracy: 0.9789
Epoch 1226/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.0371 - categorical_accuracy: 0.9930
Epoch 1227/2000
5/5 [==============================] - 0s 54ms/step - loss: 0.0394 - categorical_accuracy: 0.9859
Epoch 1228/2000
5/5 [==============================] - 0s 56ms/step - loss: 0.0307 - categorical_accuracy: 0.9930
Epoch 1229/2000
5/5 [==============================] - 0s 54ms/step - loss: 0.0289 - categorical_accuracy: 0.9930
Epoch 1230/2000
5/5 [==============================] - 0s 57ms/step - loss: 0.0328 - categorical_accuracy: 0.9930
Epoch 1231/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.0460 - categorical_accuracy: 0.9789
Epoch 1232/2000
5/5 [==============================] - 0s 55ms/step - loss: 0.0426 - categorical_accuracy: 0.9789
Epoch 1233/2000
5/5 [==============================] - 0s 74ms/step - loss: 0.0306 - cat

5/5 [==============================] - 0s 74ms/step - loss: 0.3905 - categorical_accuracy: 0.8662
Epoch 1297/2000
5/5 [==============================] - 0s 71ms/step - loss: 0.3164 - categorical_accuracy: 0.9085
Epoch 1298/2000
5/5 [==============================] - 0s 72ms/step - loss: 0.3060 - categorical_accuracy: 0.8803
Epoch 1299/2000
5/5 [==============================] - 1s 112ms/step - loss: 0.3426 - categorical_accuracy: 0.8944
Epoch 1300/2000
5/5 [==============================] - 0s 76ms/step - loss: 1.3396 - categorical_accuracy: 0.7183
Epoch 1301/2000
5/5 [==============================] - 0s 90ms/step - loss: 4.5106 - categorical_accuracy: 0.1972
Epoch 1302/2000
5/5 [==============================] - 1s 101ms/step - loss: 2.9743 - categorical_accuracy: 0.1620
Epoch 1303/2000
5/5 [==============================] - 0s 91ms/step - loss: 2.1602 - categorical_accuracy: 0.2324
Epoch 1304/2000
5/5 [==============================] - 0s 92ms/step - loss: 1.9027 - categorical_accur

Epoch 1368/2000
5/5 [==============================] - 0s 74ms/step - loss: 1.6109 - categorical_accuracy: 0.1972
Epoch 1369/2000
5/5 [==============================] - 0s 68ms/step - loss: 1.6106 - categorical_accuracy: 0.2183
Epoch 1370/2000
5/5 [==============================] - 0s 66ms/step - loss: 1.6107 - categorical_accuracy: 0.1972
Epoch 1371/2000
5/5 [==============================] - 0s 70ms/step - loss: 1.6102 - categorical_accuracy: 0.1972
Epoch 1372/2000
5/5 [==============================] - 0s 70ms/step - loss: 1.6099 - categorical_accuracy: 0.1972
Epoch 1373/2000
5/5 [==============================] - 0s 70ms/step - loss: 1.6100 - categorical_accuracy: 0.1972
Epoch 1374/2000
5/5 [==============================] - 0s 72ms/step - loss: 1.6098 - categorical_accuracy: 0.1972
Epoch 1375/2000
5/5 [==============================] - 0s 67ms/step - loss: 1.6100 - categorical_accuracy: 0.1972
Epoch 1376/2000
5/5 [==============================] - 0s 75ms/step - loss: 1.6099 - cat

5/5 [==============================] - 0s 71ms/step - loss: 1.6094 - categorical_accuracy: 0.2042
Epoch 1440/2000
5/5 [==============================] - 0s 73ms/step - loss: 1.6100 - categorical_accuracy: 0.2042
Epoch 1441/2000
5/5 [==============================] - 0s 65ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1442/2000
5/5 [==============================] - 0s 68ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1443/2000
5/5 [==============================] - 0s 67ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1444/2000
5/5 [==============================] - 0s 68ms/step - loss: 1.6098 - categorical_accuracy: 0.2042
Epoch 1445/2000
5/5 [==============================] - 0s 70ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1446/2000
5/5 [==============================] - 0s 65ms/step - loss: 1.6095 - categorical_accuracy: 0.2042
Epoch 1447/2000
5/5 [==============================] - 0s 65ms/step - loss: 1.6096 - categorical_accurac

Epoch 1511/2000
5/5 [==============================] - 0s 71ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1512/2000
5/5 [==============================] - 0s 70ms/step - loss: 1.6096 - categorical_accuracy: 0.2183
Epoch 1513/2000
5/5 [==============================] - 0s 74ms/step - loss: 1.6095 - categorical_accuracy: 0.2042
Epoch 1514/2000
5/5 [==============================] - 0s 70ms/step - loss: 1.6095 - categorical_accuracy: 0.2042
Epoch 1515/2000
5/5 [==============================] - 0s 76ms/step - loss: 1.6094 - categorical_accuracy: 0.2042
Epoch 1516/2000
5/5 [==============================] - 0s 72ms/step - loss: 1.6094 - categorical_accuracy: 0.2042
Epoch 1517/2000
5/5 [==============================] - 0s 67ms/step - loss: 1.6094 - categorical_accuracy: 0.2042
Epoch 1518/2000
5/5 [==============================] - 0s 69ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1519/2000
5/5 [==============================] - 0s 68ms/step - loss: 1.6094 - cat

5/5 [==============================] - 0s 76ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1583/2000
5/5 [==============================] - 0s 76ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1584/2000
5/5 [==============================] - 0s 76ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1585/2000
5/5 [==============================] - 0s 76ms/step - loss: 1.6095 - categorical_accuracy: 0.2042
Epoch 1586/2000
5/5 [==============================] - 0s 78ms/step - loss: 1.6095 - categorical_accuracy: 0.2042
Epoch 1587/2000
5/5 [==============================] - 0s 79ms/step - loss: 1.6093 - categorical_accuracy: 0.2042
Epoch 1588/2000
5/5 [==============================] - 0s 73ms/step - loss: 1.6093 - categorical_accuracy: 0.2042
Epoch 1589/2000
5/5 [==============================] - 0s 70ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1590/2000
5/5 [==============================] - 0s 66ms/step - loss: 1.6100 - categorical_accurac

5/5 [==============================] - 0s 64ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1655/2000
5/5 [==============================] - 0s 67ms/step - loss: 1.6094 - categorical_accuracy: 0.2042
Epoch 1656/2000
5/5 [==============================] - 0s 67ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1657/2000
5/5 [==============================] - 0s 69ms/step - loss: 1.6095 - categorical_accuracy: 0.2042
Epoch 1658/2000
5/5 [==============================] - 0s 73ms/step - loss: 1.6096 - categorical_accuracy: 0.1972
Epoch 1659/2000
5/5 [==============================] - 0s 70ms/step - loss: 1.6095 - categorical_accuracy: 0.1901
Epoch 1660/2000
5/5 [==============================] - 0s 73ms/step - loss: 1.6097 - categorical_accuracy: 0.1972
Epoch 1661/2000
5/5 [==============================] - 0s 71ms/step - loss: 1.6101 - categorical_accuracy: 0.1972
Epoch 1662/2000
5/5 [==============================] - 0s 66ms/step - loss: 1.6097 - categorical_accurac

5/5 [==============================] - 0s 83ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1727/2000
5/5 [==============================] - 0s 94ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1728/2000
5/5 [==============================] - 0s 82ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1729/2000
5/5 [==============================] - 0s 85ms/step - loss: 1.6095 - categorical_accuracy: 0.2042
Epoch 1730/2000
5/5 [==============================] - 0s 81ms/step - loss: 1.6099 - categorical_accuracy: 0.2042
Epoch 1731/2000
5/5 [==============================] - 0s 88ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1732/2000
5/5 [==============================] - 0s 80ms/step - loss: 1.6102 - categorical_accuracy: 0.2042
Epoch 1733/2000
5/5 [==============================] - 0s 74ms/step - loss: 1.6098 - categorical_accuracy: 0.1761
Epoch 1734/2000
5/5 [==============================] - 0s 76ms/step - loss: 1.6096 - categorical_accurac

5/5 [==============================] - 0s 69ms/step - loss: 1.6102 - categorical_accuracy: 0.2042
Epoch 1799/2000
5/5 [==============================] - 0s 65ms/step - loss: 1.6099 - categorical_accuracy: 0.2042
Epoch 1800/2000
5/5 [==============================] - 0s 66ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1801/2000
5/5 [==============================] - 0s 65ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1802/2000
5/5 [==============================] - 0s 66ms/step - loss: 1.6095 - categorical_accuracy: 0.2042
Epoch 1803/2000
5/5 [==============================] - 0s 65ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1804/2000
5/5 [==============================] - 0s 69ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1805/2000
5/5 [==============================] - 0s 65ms/step - loss: 1.6097 - categorical_accuracy: 0.1901
Epoch 1806/2000
5/5 [==============================] - 0s 68ms/step - loss: 1.6098 - categorical_accurac

5/5 [==============================] - 0s 65ms/step - loss: 1.6099 - categorical_accuracy: 0.2042
Epoch 1871/2000
5/5 [==============================] - 0s 67ms/step - loss: 1.6102 - categorical_accuracy: 0.2042
Epoch 1872/2000
5/5 [==============================] - 0s 65ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1873/2000
5/5 [==============================] - 0s 67ms/step - loss: 1.6095 - categorical_accuracy: 0.2042
Epoch 1874/2000
5/5 [==============================] - 0s 65ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1875/2000
5/5 [==============================] - 0s 64ms/step - loss: 1.6093 - categorical_accuracy: 0.2042
Epoch 1876/2000
5/5 [==============================] - 0s 66ms/step - loss: 1.6100 - categorical_accuracy: 0.2042
Epoch 1877/2000
5/5 [==============================] - 0s 64ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1878/2000
5/5 [==============================] - 0s 67ms/step - loss: 1.6097 - categorical_accurac

Epoch 1942/2000
5/5 [==============================] - 0s 74ms/step - loss: 1.6099 - categorical_accuracy: 0.2042
Epoch 1943/2000
5/5 [==============================] - 0s 73ms/step - loss: 1.6094 - categorical_accuracy: 0.2042
Epoch 1944/2000
5/5 [==============================] - 0s 74ms/step - loss: 1.6096 - categorical_accuracy: 0.2042
Epoch 1945/2000
5/5 [==============================] - 0s 77ms/step - loss: 1.6093 - categorical_accuracy: 0.2042
Epoch 1946/2000
5/5 [==============================] - 0s 87ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1947/2000
5/5 [==============================] - 0s 73ms/step - loss: 1.6095 - categorical_accuracy: 0.2042
Epoch 1948/2000
5/5 [==============================] - 0s 75ms/step - loss: 1.6101 - categorical_accuracy: 0.2042
Epoch 1949/2000
5/5 [==============================] - 0s 72ms/step - loss: 1.6097 - categorical_accuracy: 0.2042
Epoch 1950/2000
5/5 [==============================] - 0s 75ms/step - loss: 1.6097 - cat

In [107]:
res = model.predict(x_test)
print(res)
print(actions[np.argmax(res[0])])
for i in range(len(res)):
    print(actions[np.argmax(res[i])])

[[8.62513592e-14 1.00000000e+00 4.69410336e-29]
 [1.22290401e-24 1.00000000e+00 1.54491207e-15]
 [1.05704596e-13 1.00000000e+00 3.24167683e-29]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [2.39385379e-04 0.00000000e+00 9.99760568e-01]]
meetyou
meetyou
meetyou
meetyou
meetyou
hi


In [108]:
# save weights
model.save('action.h5')

In [109]:
#evaluation using confusion matrix
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

yhat = model.predict(x_test)
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()
matrix = multilabel_confusion_matrix(ytrue, yhat)
print(matrix)
accuracy_score = accuracy_score(ytrue, yhat)
print(f"{accuracy_score= }")


[[[3 0]
  [2 0]]

 [[1 2]
  [0 2]]

 [[4 0]
  [0 1]]]
accuracy_score= 0.6
